import { writeFile } from 'fs/promises'
import path from 'path'

import { readInternalFile } from '../utils/index.js'

const prependBanner = (str) =>
	`/** THIS FILE IS GENERATED BY ZAZEN, MANUAL CHANGES WILL BE DISCARDED. **/\n${str}`

const getPathFromCwd = (filePath) => path.join(process.cwd(), filePath)

const writeFileToCwd = async (
	fileName,
	content,
	{ banner = true, json = false } = {}
) => {
	let outPath = getPathFromCwd(fileName)
	let str = json ? JSON.stringify(content, null, 2) : content
	let contentStr = banner ? prependBanner(str) : str

	await writeFile(outPath, contentStr)
}

/**
 * This is the main function.
 *
 * @export
 */
export default async function () {
	/** @todo Detect if project is a module and change name to .cjs. */
	let eslintConfigFile = '.eslintrc.js'
	let eslintConfig = await readInternalFile('../.eslintrc.cjs')

	await writeFileToCwd(eslintConfigFile, eslintConfig)

	let prettierConfigFile = 'prettier.config.js'
	let prettierConfig = await readInternalFile('../config/prettier.js')
	await writeFileToCwd(prettierConfigFile, prettierConfig)
}
