name: CI

on: [push]

jobs:
  test:
    name: Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.x']

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@v3

      # https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v2
        with:
          version: 6

      # https://github.com/actions/setup-node
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Build
      #   run: npm run build

      # - name: Lint
      #   run: npm run lint

      - name: Test
        run: npm test
